--- a/libavcodec/riscv/Makefile
+++ b/libavcodec/riscv/Makefile
@@ -1,3 +1,8 @@
+OBJS-$(CONFIG_SBRDSP)                 += riscv/sbrdsp_init.o
+
+RVV-OBJS-$(CONFIG_SBRDSP)             += riscv/sbrdsp_rvv.o
+
+# TODO: If this Makefile already defines RVV-OBJS / OBJS patterns, integrate these lines.
