--- a/libavcodec/riscv/Makefile
+++ b/libavcodec/riscv/Makefile
@@ -0,0 +1,6 @@
+#
+# RISC-V optimizations
+#
+
+OBJS-$(CONFIG_H264PRED)               += riscv/h264pred_rvv.o riscv/h264pred_init_riscv.o
+